import java.util.*;
	public class Ex3_14 {
		public static void main (String [] args) {
			Scanner input = new Scanner(System.in);
			System.out.println("Predict heads or tails"); 
			String guess = input.nextLine();
			input.close();
			
			Random rand = new Random();
			int answer = rand.nextInt(2);

			String key = "";

			if (answer == 0) {
				key = "tails";
			}

			else if (answer == 1) {
				 key = "heads";
			}

			int qwerty = 0;

			if ( guess == "heads") {
				qwerty = 1;
			}
			else if ( guess == "tails") {
				 qwerty = 0;
			}

			if ( qwerty == answer) {
				System.out.println("Correct!! Answer was " + guess + " generated by binary " + qwerty);
			}
			else if (qwerty != answer) {
				System.out.println("WRONG! Try again. Answer was " + key + " generated by binary " + answer);
			}
		}
}